// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_byteme from "./routes/api/byteme.ts";
import * as $api_getShareData from "./routes/api/getShareData.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_pingperfect from "./routes/api/pingperfect.ts";
import * as $api_servusspeed from "./routes/api/servusspeed.ts";
import * as $api_share from "./routes/api/share.ts";
import * as $api_verbyndich from "./routes/api/verbyndich.ts";
import * as $api_webwunder from "./routes/api/webwunder.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ComparisonBox from "./islands/ComparisonBox.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Inputfield from "./islands/Inputfield.tsx";
import * as $ResultPage from "./islands/ResultPage.tsx";
import * as $apicallmethod from "./islands/apicallmethod.ts";
import * as $product from "./islands/product.ts";
import * as $state from "./islands/state.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/byteme.ts": $api_byteme,
    "./routes/api/getShareData.ts": $api_getShareData,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/pingperfect.ts": $api_pingperfect,
    "./routes/api/servusspeed.ts": $api_servusspeed,
    "./routes/api/share.ts": $api_share,
    "./routes/api/verbyndich.ts": $api_verbyndich,
    "./routes/api/webwunder.ts": $api_webwunder,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ComparisonBox.tsx": $ComparisonBox,
    "./islands/Counter.tsx": $Counter,
    "./islands/Inputfield.tsx": $Inputfield,
    "./islands/ResultPage.tsx": $ResultPage,
    "./islands/apicallmethod.ts": $apicallmethod,
    "./islands/product.ts": $product,
    "./islands/state.ts": $state,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
